version: "3"

networks:
  app_bridge:
    driver: bridge
    
services:
  crawler:
    build: 
      context: ..
      dockerfile: Deploy/Crawler/Dockerfile
    restart: always
    networks:
      - app_bridge