version: "3"

networks:
  app_bridge:
    driver: bridge
    
services:
  api:
    build: 
      context: ..
      dockerfile: Deploy/API/Dockerfile
    container_name: peepapi_container
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "8080:80"
    depends_on:
      - rabbitmq
      - redis
      - db
    networks:
      - app_bridge

  rabbitmq: 
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_bridge

  redis:
    image: redis:buster
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_bridge
        
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app_bridge
      
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - app_bridge