version: "3"

networks:
  app_bridge:
    driver: bridge
    
services:
  api:
    build: 
      context: ..
      dockerfile: Deploy/API/Dockerfile
      args:
        ASPNET_VERSION: 3.1
        SDK_VERSION: 3.1
    container_name: peepapi_container
    ports:
      - "8080:80"
    depends_on:
      - rabbitmq
      - redis
      - db
    networks:
      - app_bridge

  crawler:
    build: 
      context: ..
      dockerfile: Deploy/Crawler/Dockerfile
      args:
        ASPNET_VERSION: 3.1
        SDK_VERSION: 3.1
    scale: 2
    depends_on:
      - rabbitmq
      - redis
      - db
    networks:
      - app_bridge

  rabbitmq: 
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_bridge

  redis:
    image: redis
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - app_bridge
        
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_DATABASE: peep
      MYSQL_ROOT_PASSWORD: password
    networks:
      - app_bridge
      
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - app_bridge