version: "2"
services:
  api:
    build: 
      context: ..
      dockerfile: Deploy/API/Dockerfile
      args:
        ASPNET_VERSION: 3.1
        SDK_VERSION: 3.1
    container_name: peepapi_container
    ports:
      - "8080:80"
    depends_on:
      - rabbitmq
      - redis

  crawler:
    build: 
      context: ..
      dockerfile: Deploy/Crawler/Dockerfile
      args:
        ASPNET_VERSION: 3.1
        SDK_VERSION: 3.1
    container_name: peepcrawler_container
    depends_on:
      - rabbitmq
      - redis

  rabbitmq: 
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
      
  redis:
    image: redis
    container_name: redis_container
    ports:
      - "6379:6379"